global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'babelbit-validator'
    static_configs:
      - targets: ['validator:8000']
        labels:
          instance: validator

  - job_name: 'babelbit-runner'
    static_configs:
      - targets: ['runner:8000']
        labels:
          instance: runner
